--insert into dps_organization(id,name,short_name,slogan,ruc,img,phone,address,web)
--values
--(1,'Municipalidad del Centro Poblado Santa Maria de Huachipa','SMH','Trabajando por el cambio','20144642152','Esto es una imagen','930721163','Av Los Canarios 45','http://www.vertabelo.com'),
--(2,'Municipalidad de Huachipa','Trabajando por el cambio','MCPSMH','20144642152','Esto es una imagen','930721163','Av Los Cisnes 22','http://www.vertabelo.com');

--insert into tupa(id,name,year,resolution,pdffile)
--values
--(1,'TUPA DEL AÑO 2012',2012,'RESOLUCION 123213 TUO DS','Esto es un archivo PDF'),
--(2,'TUPA DEL AÑO 2013',2015,'RESOLUCION 123213 TUO DS','Esto es un archivo PDF');
--
--insert into work(id,idorganization,name,year,uit,idtupa)
--values
--(1,1,'Año del buen servicio al ciudadano',2018,4150.00,1);

--insert into requisite(id,nombre,descripcion)
--	values
--	(1,'Solicitud simple','Solicitud simple'),
--	(2,'Constancia de Posesion','Constancia de Posesion'),
--	(3,'Copia de Dni','Copia de Dni'),
--	(4,'Ficha Ruc','Ficha Ruc'),
--	(5,'Planes de evacuacion','Planes de evacuacion'),
--	(6,'Certificado de Defensa Civil','Certificado de Defensa Civil');
--
--
--insert into dps_office (id,name,short_name,description,active)
--values
--(1,'SUBGEREMCIA DE INFORMATICA','SGI','Oficina de la Sub Gerencia de Informatica',0),
--(2,'GEREMCIA DE ADMINISTRACION TRIBUTARIA','GAT','Oficina de la Gerencia de Administracion Tributaria',1),
--(3,'SUBGEREMCIA DE INFORMATICA','SGI','Oficina de la Sub Gerencia de Informatica',1);

--insert into dps_user(id,username,password,role)
--values
--(1,'user','password', 'ROLE_USER'),
--(2,'admin','password', 'ROLE_ADMIN');